
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/twwin?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
      minimum-idle: 10
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: select 'connected'

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

